name: create-gif

on:
  workflow_dispatch:
  schedule:
    - cron:  '5,35 * * * *'
jobs:
  create-gif:
    runs-on: windows-latest
    env:
      RENV_PATHS_ROOT: ~/AppData/Local/renv
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        
      - uses: r-lib/actions/setup-r@v1
        name: Setup R
        
      - uses: r-lib/actions/setup-pandoc@master
        name: Setup Pandoc
         
      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv23-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv23-

      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
        
      - name: Run bot
        run: Rscript R/trigger.R
        
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m 'Run bot' || echo "No changes to commit"
          git push origin || echo "No changes to commit"

